AWSTemplateFormatVersion: 2010-09-09
Description: CHAOSSEARCH Lambda Template
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - 
        Label:
          default: "AWS Acccount Information"
        Parameters:
          - AWSAccountID
          - AWSRegion
      - 
        Label: 
          default: "Resource Names"
        Parameters:
          - LambdaIAMPolicyName
          - LambdaIAMRoleName
          - LambdaFunctionName
      -
        Label:
          default: "Other Information"
        Parameters:
          - KinesisFirehoseDeliveryStreamName
          - SSACCOUNTNAME
          - SSREGION
          - SSVPCID
          - S3Bucket
          - S3ObjectKey
    ParameterLabels:
      AWSAccountID:
        default: "The AWS Account ID"
      AWSRegion:
        default: "The AWS Region"
      LambdaIAMPolicyName: 
        default: "The IAM Policy name"
      LambdaIAMRoleName: 
        default: "The IAM Role name"
      LambdaFunctionName: 
        default: "The Lambda Function name"
      KinesisFirehoseDeliveryStreamName:
        default: "The Kinesis Firehose Delivery Stream name"
      SSACCOUNTNAME:
        default: "The 6th Street Account Name"
      SSREGION:
        default: "The 6th Street Region"
      SSVPCID:
        default: "The 6th Street VPC ID"
      S3Bucket:
        default: "The s3 bucket"
      S3ObjectKey:
        default: "The s3 object key"
Parameters:
  AWSAccountID:
    Description: "Your AWS Account ID"
    Type: String
    Default: 772467465859
  AWSRegion:
    Description: "The AWS Region"
    Type: String
    Default: us-east-1
  LambdaIAMPolicyName:
    Description: "What name do you want to give for the IAM Policy?"
    Type: String
  LambdaIAMRoleName:
    Description: "What name do you want to give for the IAM Role?"
    Type: String
  LambdaFunctionName:
    Description: "What name do you want to give for the Lambda Function?"
    Type: String
  KinesisFirehoseDeliveryStreamName:
    Description: "The name of the Kinesis Firehose Delivery Stream to attached the lambda function to."
    Type: String
  SSACCOUNTNAME: 
    Description: "What is the 6th Street account name? (i.e. feddev)"
    Type: String
  SSREGION:
    Description: "What is the 6th Street region? (i.e. use2)"
    Type: String
  SSVPCID:
    Description: "What is the 6th Street vpc id? (i.e. vpc06ff6b453726b41b1)"
    Type: String
  S3Bucket:
    Description: "What is the s3 bucket that contains the lambda code?"
    Type: String
    Default: td-lambda-functions
  S3ObjectKey:
    Description: "What is the s3 object key for the lambda code?"
    Type: String
    Default: td-ssm-log-processor-c38a66be-2b0d-4208-8f0d-30cb79779bdf.zip
Resources:
  LambdaPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub ${LambdaIAMPolicyName}
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 'logs:CreateLogGroup'
            Resource: !Sub 'arn:aws:logs:${AWSRegion}:${AWSAccountID}:*'
          - Effect: Allow
            Action:
              - 'logs:CreateLogStream'
              - 'logs:PutLogEvents'
            Resource: !Sub 'arn:aws:logs:${AWSRegion}:${AWSAccountID}:log-group:/aws/lambda/${LambdaFunctionName}:*'
          - Effect: Allow
            Action:
              - 'firehose:PutRecordBatch'
            Resource: !Sub 'arn:aws:firehose:${AWSRegion}:${AWSAccountID}:deliverystream/${KinesisFirehoseDeliveryStreamName}'
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${LambdaIAMRoleName}
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns: 
        - !Ref LambdaPolicy
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${LambdaFunctionName}
      Role: !GetAtt LambdaRole.Arn
      Runtime: python3.8
      Handler: lambda_function.lambda_handler
      Timeout: 180
      Environment:
        Variables:
          SS_ACCOUNT_NAME: !Sub ${SSACCOUNTNAME}
          SS_REGION: !Sub ${SSREGION}
          SS_VPCID: !Sub ${SSVPCID}
      Code:
        S3Bucket: !Sub '${S3Bucket}'
        S3Key: !Sub '${S3ObjectKey}'